# Generated by Django 4.1.5 on 2023-04-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=117)),
                ('size', models.CharField(max_length=117)),
                ('friendliness', models.IntegerField()),
                ('trainability', models.IntegerField()),
                ('sheddingamount', models.IntegerField()),
                ('exerciseneeds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=117)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=117)),
                ('color', models.CharField(max_length=117)),
                ('favoritefood', models.CharField(max_length=117)),
                ('favoritetoy', models.CharField(max_length=117)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.breed')),
            ],
        ),
    ]
